### ISSUE TITLE
There is something wrong with generate command and BUILD file.

### ISSUE THREAD

**Issue by willbetheone** [philippschw/handtracking_app#1]
Thanks for your code, it help me get to know the mediapipe on iOS faster.

The build file is not available，Could you  provide a available BUILD file and the build command？

**Comment by philippschw** [comment]
Hi @willbetheone , did you follow the [README.md ](https://github.com/philippschw/handtracking_app/blob/master/README.md)? What step fails for you and where do you think something is missing? Please note that this repo only works if you also have cloned the main mediapipe repo. https://github.com/google/mediapipe.

**Comment by willbetheone** [comment]
There is a error when I perform  Step 3 with main mediapipe repo.
The error in the under image.
<img width="1132" alt="1" src="https://user-images.githubusercontent.com/42705961/150110656-f1c637a5-e7e8-4ff7-ad2c-0a3871355e53.png">
It could be caused by "step 2" so I copy the handmodelframework folder to the path(./mediapipe/mediapipe/examples/ios).
And rebuild with step 3.

**Comment by willbetheone** [comment]
There is a error when I perform  Step 3 with main mediapipe repo.
**Step 1:**
The error 1 in the under image.
<img width="1132" alt="1" src="https://user-images.githubusercontent.com/42705961/150110656-f1c637a5-e7e8-4ff7-ad2c-0a3871355e53.png">
It could be caused by "step 2" so I copy the handmodelframework folder to the path(./mediapipe/mediapipe/examples/ios).

**Step 2:**
And rebuild with step 3 with "bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/posetrackingframework:PoseTracker"

Still report an error 2，I found the build command is maybe mistake，as shown below.
<img width="1126" alt="2" src="https://user-images.githubusercontent.com/42705961/150114344-29e2234f-90ed-41ed-9a75-3a38ca37fd39.png">

**Step 3:**
I guess the build script is mistake. so I rebuild with this script "bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handmodelframework:HandTracker".

Still report an error 3. as shown below. 
<img width="1137" alt="3" src="https://user-images.githubusercontent.com/42705961/150115809-212eae4f-848b-4b6d-a21c-531c5af3a21f.png">
So I guess the BUILD file and build script is  is not available，Could you provide a available BUILD file and the build command？

**Comment by willbetheone** [comment]
I fix Build file and build sucessed.  Thank you for your code. 👍🏻👍🏻👍🏻
